covariance:
    prior:
        pos: 1.0e-6
        vel: 1.0e-6
        ori: 1.0e-6
        epsilon: 1.0e-6
        delta: 1.0e-6
    process:
        gyro: 1.0e-4
        accel: 2.5e-3
        bias_accel: 2.5e-3
        bias_gyro: 1.0e-4
    measurement:
        pose:
            pos: 1.0e-4
            ori: 1.0e-4
        pos: 1.0e-4
        vel: 2.5e-3
motion_constraint: 
    activated: true
    w_b_thresh: 0.13

odom_or_vel: true
# odom_or_vel: false   


# imu_topic: "/kitti/oxts/imu/extract"
imu_topic: "/imu"

