(cl:defpackage lidar_localization-srv
  (:use )
  (:export
   "SAVEODOMETRY"
   "<SAVEODOMETRY-REQUEST>"
   "SAVEODOMETRY-REQUEST"
   "<SAVEODOMETRY-RESPONSE>"
   "SAVEODOMETRY-RESPONSE"
   "SAVESCANCONTEXT"
   "<SAVESCANCONTEXT-REQUEST>"
   "SAVESCANCONTEXT-REQUEST"
   "<SAVESCANCONTEXT-RESPONSE>"
   "SAVESCANCONTEXT-RESPONSE"
  ))

